export const projects_wide = [
  {
    id: '10',
    works: [
      {
        name: 'portfolio site',
        date: '04.2019',
        demo: 'https://eliotmess.github.io/my-portfolio/',
        img: 'works/works_portfolio.jpg',
        github: 'https://github.com/eliotmess/my-portfolio',
        id: '1',
        tech: [
          'Gatsby.js',
          'styled components',
          'JS (ES6+)',
          'React.js',
          'HTML5',
        ],
      },
      {
        name: 'e-commerce PWA',
        date: '03.2019',
        demo: 'https://v-dreams.firebaseapp.com/',
        img: 'works/works_ecom.jpg',
        github: 'https://github.com/eliotmess/ecom',
        id: '3',
        tech: [
          'React.js',
          'Redux',
          'JS (ES6+)',
          'HTML5',
          'Sass (SCSS)',
          'Firebase (PWA)',
        ],
      },
      {
        name: 'rock-paper-scissors',
        date: '10.2018',
        demo: 'https://eliotmess.github.io/rock_paper_scissors/',
        img: 'works/works_rps.jpg',
        github: 'https://github.com/eliotmess/rock_paper_scissors',
        id: '2',
        tech: ['HTML5', 'Sass (SCSS)', 'JS (ES5)', 'vanilla JS', 'CSS3'],
      },
    ],
  },
  {
    id: '11',
    works: [
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'https://google.com',
        img: 'works/works_portfolio.jpg',
        github: 'https://google.com',
        id: '4',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'https://google.com',
        img: 'works/works_portfolio.jpg',
        github: 'https://google.com',
        id: '5',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
    ],
  },
];

export const projects_two_cols = [
  {
    id: '10',
    works: [
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'https://google.com',
        img: 'works/works_portfolio.jpg',
        github: 'https://google.com',
        id: '1',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'https://google.com',
        img: 'works/works_portfolio.jpg',
        github: 'https://google.com',
        id: '2',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
    ],
  },
  {
    id: '11',
    works: [
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'https://google.com',
        img: 'works/works_portfolio.jpg',
        github: 'https://google.com',
        id: '3',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'https://google.com',
        img: 'works/works_portfolio.jpg',
        github: 'https://google.com',
        id: '4',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
    ],
  },
  {
    id: '12',
    works: [
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'https://google.com',
        img: 'works/works_portfolio.jpg',
        github: 'https://google.com',
        id: '5',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'https://google.com',
        img: 'works/works_portfolio.jpg',
        github: 'https://google.com',
        id: '6',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
    ],
  },
];

export const projects_one_col = [
  {
    id: '10',
    works: [
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'https://google.com',
        github: 'https://google.com',
        img: 'works/works_portfolio.jpg',
        id: '1',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
    ],
  },
  {
    id: '11',
    works: [
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'https://google.com',
        github: 'https://google.com',
        img: 'works/works_portfolio.jpg',
        id: '2',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
    ],
  },
  {
    id: '12',
    works: [
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'https://google.com',
        github: 'https://google.com',
        img: 'works/works_portfolio.jpg',
        id: '3',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
    ],
  },
  {
    id: '13',
    works: [
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'https://google.com',
        github: 'https://google.com',
        img: 'works/works_portfolio.jpg',
        id: '4',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
    ],
  },
  {
    id: '14',
    works: [
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'https://google.com',
        github: 'https://google.com',
        img: 'works/works_portfolio.jpg',
        id: '5',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
    ],
  },
];
