export const projects_wide = [
  {
    id: '10',
    works: [
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'http://google.com',
        github: 'http://google.com',
        id: '1',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'http://google.com',
        github: 'http://google.com',
        id: '2',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'http://google.com',
        github: 'http://google.com',
        id: '3',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
    ],
  },
  {
    id: '11',
    works: [
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'http://google.com',
        github: 'http://google.com',
        id: '4',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'http://google.com',
        github: 'http://google.com',
        id: '5',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'http://google.com',
        github: 'http://google.com',
        id: '6',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
    ],
  },
];

export const projects_two_cols = [
  {
    id: '10',
    works: [
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'http://google.com',
        github: 'http://google.com',
        id: '1',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'http://google.com',
        github: 'http://google.com',
        id: '2',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
    ],
  },
  {
    id: '11',
    works: [
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'http://google.com',
        github: 'http://google.com',
        id: '3',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'http://google.com',
        github: 'http://google.com',
        id: '4',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
    ],
  },
  {
    id: '12',
    works: [
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'http://google.com',
        github: 'http://google.com',
        id: '5',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
      {
        name: 'v-dreams e-commerce',
        date: '03.2019',
        demo: 'http://google.com',
        github: 'http://google.com',
        id: '6',
        tech: [
          'HTML5',
          'CSS3',
          'Sass (SCSS)',
          'React.js',
          'JS (ES6+)',
          'Redux',
          'Firebase',
        ],
      },
    ],
  },
];

export const projects_one_col = [
  {
    name: 'v-dreams e-commerce',
    date: '03.2019',
    demo: 'http://google.com',
    github: 'http://google.com',
    id: '1',
    tech: [
      'HTML5',
      'CSS3',
      'Sass (SCSS)',
      'React.js',
      'JS (ES6+)',
      'Redux',
      'Firebase',
    ],
  },
  {
    name: 'v-dreams e-commerce',
    date: '03.2019',
    demo: 'http://google.com',
    github: 'http://google.com',
    id: '2',
    tech: [
      'HTML5',
      'CSS3',
      'Sass (SCSS)',
      'React.js',
      'JS (ES6+)',
      'Redux',
      'Firebase',
    ],
  },
  {
    name: 'v-dreams e-commerce',
    date: '03.2019',
    demo: 'http://google.com',
    github: 'http://google.com',
    id: '3',
    tech: [
      'HTML5',
      'CSS3',
      'Sass (SCSS)',
      'React.js',
      'JS (ES6+)',
      'Redux',
      'Firebase',
    ],
  },
  {
    name: 'v-dreams e-commerce',
    date: '03.2019',
    demo: 'http://google.com',
    github: 'http://google.com',
    id: '4',
    tech: [
      'HTML5',
      'CSS3',
      'Sass (SCSS)',
      'React.js',
      'JS (ES6+)',
      'Redux',
      'Firebase',
    ],
  },
  {
    name: 'v-dreams e-commerce',
    date: '03.2019',
    demo: 'http://google.com',
    github: 'http://google.com',
    id: '5',
    tech: [
      'HTML5',
      'CSS3',
      'Sass (SCSS)',
      'React.js',
      'JS (ES6+)',
      'Redux',
      'Firebase',
    ],
  },
  {
    name: 'v-dreams e-commerce',
    date: '03.2019',
    demo: 'http://google.com',
    github: 'http://google.com',
    id: '6',
    tech: [
      'HTML5',
      'CSS3',
      'Sass (SCSS)',
      'React.js',
      'JS (ES6+)',
      'Redux',
      'Firebase',
    ],
  },
];
